# Do not modify this file! (don't tell me what to do!) It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  config = {
    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    blocks.persist.path = "/nix/persist";
  
    fileSystems = {
      "/" = { 
        device = "none";
        fsType = "tmpfs";
        options = [ "defaults" "size=3G" "mode=755" ];
      };
    
      "/etc/passwords" = { 
        device = "/nix/persist/system/etc/passwords";
        fsType = "none";
        options = [ "bind" ];
        neededForBoot = true;
      };
  
      "/boot" = { 
        device = "/dev/disk/by-uuid/B35B-71DB";
        fsType = "vfat";
      };
  
      "/nix" = { 
        device = "/dev/disk/by-uuid/16b17eae-c8a9-48e1-bff2-466c327308b1";
        fsType = "ext4";
        neededForBoot = true;
      };
    };
  
    swapDevices = [ ];
  
    powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
